### ISSUE TITLE
Version bounds missing on swagger2 dependency

### ISSUE THREAD

**Issue by phlummox** [softwarefactory-project/podman-haskell#1]
In the `podman-codegen` [.cabal file][codegen-cabal], no version bounds are placed on the `swagger2` dependency. However, it looks like the bounds should be

```
swagger2            >= 2.4
```

as breaking changes were made in that version of swagger2, and podman-haskell won't compile with earlier versions.

[codegen-cabal]: https://github.com/softwarefactory-project/podman-haskell/blob/4457ccdf5570e4bdb85fd8dde504244662adc1b3/podman-codegen/podman-codegen.cabal#L33

**Comment by TristanCacqueray** [comment]
@phlummox Thanks! Note that project needs to be updated now that the swagger inconsistencies have been fixed upstream, please let me know if you need help with that.

**Comment by phlummox** [comment]
Will do :)

Actually, I had a query - I notice your record fields all start with an underscore ("_"), which usually signifies the field's going to be accessed via a [Lens][lens] ... but no lenses are generated. Was this intentional?

[lens]: https://hackage.haskell.org/package/microlens-0.4.12.0/docs/Lens-Micro.html#g:4

**Comment by TristanCacqueray** [comment]
I don't have a use case for lens, but I'd be happy to have them if needed.

**Comment by phlummox** [comment]
Ah no worries - I just wondered why the fields were named that way. Cheers!
